//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freengy.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Freengy.Localization.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban.
        /// </summary>
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel activities.
        /// </summary>
        public static string CancelActivities {
            get {
                return ResourceManager.GetString("CancelActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Freengy.CommonResources;component/Images/DefaultGameIcon.png.
        /// </summary>
        public static string DefaultGameIconUri {
            get {
                return ResourceManager.GetString("DefaultGameIconUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting.
        /// </summary>
        public static string Disconnecting {
            get {
                return ResourceManager.GetString("Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit account data.
        /// </summary>
        public static string EditAccountData {
            get {
                return ResourceManager.GetString("EditAccountData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spaces, template: good@email.
        /// </summary>
        public static string EmailRequirementsText {
            get {
                return ResourceManager.GetString("EmailRequirementsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Empty&gt;.
        /// </summary>
        public static string EmptyPlaceHolder {
            get {
                return ResourceManager.GetString("EmptyPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; doesnt match requirements &apos;{1}&apos;.
        /// </summary>
        public static string EntityDoesntMatchRequirementsFormat {
            get {
                return ResourceManager.GetString("EntityDoesntMatchRequirementsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string FinishedText {
            get {
                return ResourceManager.GetString("FinishedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string FinishText {
            get {
                return ResourceManager.GetString("FinishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string ForgotPasswordQuestionText {
            get {
                return ResourceManager.GetString("ForgotPasswordQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend updates will be here.
        /// </summary>
        public static string FriendUpdatesWillBeHere {
            get {
                return ResourceManager.GetString("FriendUpdatesWillBeHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname.
        /// </summary>
        public static string HostNameText {
            get {
                return ResourceManager.GetString("HostNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am.
        /// </summary>
        public static string IAm {
            get {
                return ResourceManager.GetString("IAm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string IgnoreText {
            get {
                return ResourceManager.GetString("IgnoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string InProgressText {
            get {
                return ResourceManager.GetString("InProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s be friends!.
        /// </summary>
        public static string LetsBeFriends {
            get {
                return ResourceManager.GetString("LetsBeFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Expirience.
        /// </summary>
        public static string LevelExpirience {
            get {
                return ResourceManager.GetString("LevelExpirience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingDotsText {
            get {
                return ResourceManager.GetString("LoadingDotsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in and kawabanga!.
        /// </summary>
        public static string LogInWelcomeText {
            get {
                return ResourceManager.GetString("LogInWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My albums.
        /// </summary>
        public static string MyAlbums {
            get {
                return ResourceManager.GetString("MyAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not not required, but you will be unable to recover forgotten password without it.
        /// </summary>
        public static string NewAccountEmailHintText {
            get {
                return ResourceManager.GetString("NewAccountEmailHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow! New friend request.
        /// </summary>
        public static string NewFriendRequestNotice {
            get {
                return ResourceManager.GetString("NewFriendRequestNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server сonnection.
        /// </summary>
        public static string NoServerConnection {
            get {
                return ResourceManager.GetString("NoServerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length of 10 symbols and no spaces.
        /// </summary>
        public static string PasswordRequirementsText {
            get {
                return ResourceManager.GetString("PasswordRequirementsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege.
        /// </summary>
        public static string Privilege {
            get {
                return ResourceManager.GetString("Privilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to freengy@host.net.
        /// </summary>
        public static string ProjectFakeEmail {
            get {
                return ResourceManager.GetString("ProjectFakeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freengy.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover your password.
        /// </summary>
        public static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterText {
            get {
                return ResourceManager.GetString("RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveText {
            get {
                return ResourceManager.GetString("RemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request route not found on server.
        /// </summary>
        public static string RequestRouteNotFound {
            get {
                return ResourceManager.GetString("RequestRouteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save password.
        /// </summary>
        public static string SavePasswordText {
            get {
                return ResourceManager.GetString("SavePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for friends.
        /// </summary>
        public static string SearchFriends {
            get {
                return ResourceManager.GetString("SearchFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for new awesome friends!.
        /// </summary>
        public static string SearchNewAwesomeFriends {
            get {
                return ResourceManager.GetString("SearchNewAwesomeFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server offline.
        /// </summary>
        public static string ServerOffline {
            get {
                return ResourceManager.GetString("ServerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server online.
        /// </summary>
        public static string ServerOnline {
            get {
                return ResourceManager.GetString("ServerOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show info.
        /// </summary>
        public static string ShowInfoText {
            get {
                return ResourceManager.GetString("ShowInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start chat.
        /// </summary>
        public static string StartChat {
            get {
                return ResourceManager.GetString("StartChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessText {
            get {
                return ResourceManager.GetString("SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserNameText {
            get {
                return ResourceManager.GetString("UserNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be empty.
        /// </summary>
        public static string ValueCannotBeEmptyFormat {
            get {
                return ResourceManager.GetString("ValueCannotBeEmptyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; contains invalid symbols.
        /// </summary>
        public static string ValuesContainsInvalidSymbols {
            get {
                return ResourceManager.GetString("ValuesContainsInvalidSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your friend.
        /// </summary>
        public static string YourFriend {
            get {
                return ResourceManager.GetString("YourFriend", resourceCulture);
            }
        }
    }
}
